### PR TITLE
Merge 1.7-civi branch into 1.8-civi branch

### PR DESCRIPTION
**Pull request by mfb**

### CODE REVIEW

**Comment by mlutfy** [comment]
Seems good to me. @totten ?

**Comment by mfb** [comment]
See also https://github.com/civicrm/civicrm-core/pull/13799

**Comment by eileenmcnaughton** [comment]
@mlutfy looks like this has to go in since I merged the other

**Comment by eileenmcnaughton** [comment]
(I have no merge rights here)

**Comment by JohnFF** [comment]
@mfb I had the same issue with the @ character. Does this need to be backslashed  here as well?

**Pull request merged**
